name: Build and Deploy
on:
  push:
    branches:
      - "feature/39-integrate-auth"
    
env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        env:
          REACT_APP_SERVER_URL: ${{ vars.BACKEND_URL }}
        with:
          context: .
          file: ./infrastructure/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/frontend:${{ env.IMAGE_TAG }}

  build_cloud_infrastructure:
    needs: push_to_registry
    name: Build Google Cloud Infrastructure
    runs-on: ubuntu-latest
    env:
      TF_VAR_docker_tag: ${{ github.sha }}
    defaults:
      run:
        working-directory: ./infrastructure
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      
      - name: Terraform format
        run: terraform fmt -check

      - name: Terraform plan
        run: terraform plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      
      - name: Terraform apply
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}


